### PR TITLE
build: add script to gen nuxt3 style directory structure

### PR DESCRIPTION
**Pull request by initdc**
Signed-off-by: initdc <initd@outlook.com>

### CODE REVIEW

**Comment by danielroe** [comment]
Thanks, but I don't think this is the right approach here. We have [`nuxi add`](https://nuxt.com/docs/api/commands/add/) and are discussing providing a more full-featured template: https://github.com/nuxt/starter/issues/134.

**Comment by initdc** [comment]
I think a visible file directory is more motivating than an api hidden in a document,
 and that's been the style since nuxt 2,  we want that.

Creating folders does not conflict with using `nuxi add` either.

**Comment by atinux** [comment]
I think it is related to #134 as we should have a more beginner-friendly template instead

**Comment by danielroe** [comment]
Closing this to track in #134 instead. Thank you for the idea.

**Pull request closed without merging**
