### PR TITLE
docs: add sidebase template

### PR DESCRIPTION
**Pull request by BracketJohn**
As per https://github.com/unjs/giget/pull/16#issuecomment-1248239083 I want to add [sidebase](https://github.com/sidestream-tech/sidebase) as a template, so that it can be used via the `nuxi init` command (: 

As per https://github.com/sidestream-tech/sidebase/issues/33 we will talk on twitter about this after:
- [x] https://github.com/sidestream-tech/sidebase/pull/34
- [ ] this PR was merged
- [ ] sidebase-docs were updated

### CODE REVIEW

**Comment by BracketJohn** [comment]
@pi0 next attempt - let's hope I did the right thing this time. Would be happy for a review / merge 🥇

**Comment by pi0** [comment]
Thanks! Waiting to review from @Atinux as well. I think we _might_ also move it to `templates/community` making clonnable as `nuxi init -t community/sidebase`.

**Comment by BracketJohn** [comment]
Alrighty, thanks! Looking forward for what @Atinux has to say (: As we followed his recent suggestion and flattened `sidebase` (removing the in-between `app/` folder) he's hopefully happy with it ☺️

**Comment by pi0** [comment]
Related question: Have you tried `extends`/`theme` feature? Currently this starter clones whole `sidestream-tech/sidebase` repository. Meaning if you make any improvements, users have to create a new project or manually update them. We could convert `sidebase` to a theme (or a base project) and extend it from starter. Users have all of side-base project.

Here is an example structure for theme: https://github.com/nuxt/starter/tree/theme

**Comment by danielroe** [comment]
`community/sidebase` seems good to me 👍

**Comment by BracketJohn** [comment]
> Related question: Have you tried extends/theme feature? 

No, we have not, but it looks superb. Some qs:
- is there more docs than [this example project](https://v3.nuxtjs.org/examples/advanced/config-extends#config-extends) and the [nuxt.config.ts](https://v3.nuxtjs.org/api/configuration/nuxt.config#extends) page on this? 
  - what's the difference between `theme` and `extends`? the docs are almost the same
- where can I look into the "patch algorithm" (if no docs exist)? it seems like there must be some shortcomings like when names duplicate or some config is double specified

It looks cool though - like the future of starters / templates. I do love very much that it's versioned (it's a major shortcoming we identified and the reason why we already slowly started to make some of our code npm packages like https://www.npmjs.com/package/@sidestream-tech/nuxt-sidebase-parse)

For now I would try to get this PR merged and then in the next biggish iteration switch over to the `theme` / `extends` approach. Is that OK for you?

**Comment by pi0** [comment]
> what's the difference between theme and extends? the docs are almost the same

They are the same aliases. `theme` is singular and more specific for one layer extending

> where can I look into the "patch algorithm" (if no docs exist)? it seems like there must be some shortcomings like when names duplicate or some config is double specified

Can you please explain more about name duplicate? Config is merged via [defu](https://www.npmjs.com/package/defu) (user project having highest priority). 

> I do love very much that it's versioned

Surely this is on of the main benefits of supporting extends instead of classic **full template clone**. You can either use github tags or publish repo as an npm package to version.

**Comment by atinux** [comment]
I believe for now it's good to start with `community/sidebase`.

Next will be to see how Sidebase could become a theme by leveraging the `extends` feature, definitely need to document it and add more examples to explain the full power of it!

**Comment by BracketJohn** [comment]
> Can you please explain more about name duplicate? Config is merged via [defu](https://www.npmjs.com/package/defu) (user project having highest priority).

sure -  I'm wondering:
- what files, folders, configs, ... can all be part of a theme? E.g.: can a `vitest.config.ts` also be specified?
- precedence:
  - if a collision happens, what takes precedence? -> you already said user-project here
  - is it a "winner takes all" merge or (somehow) a deep merge? does this differ for files vs. config objects?
  - is there a way to ensure that a merge will never happen? E.g., when we have a `setupTestEnv.ts` file that we always want to merge in as it makes sense no matter what?

> Surely this is on of the main benefits of supporting extends instead of classic full template clone. You can either use github tags or publish repo as an npm package to version.

AFAIU this line at least provides a decent workaround:
```json
  "tar": "https://codeload.github.com/sidestream-tech/sidebase/tar.gz/refs/heads/main"
```

as we could specify specific branches or other valid git refs. But yeah, npm style semver with an established packaging mechanism would be much preferred.

> I believe for now it's good to start with community/sidebase.

Agreed (: Would be nice to get this merged then.

**Comment by atinux** [comment]
Shall it be renamed to `templates/community/sidebase.json` @pi0 ?

**Comment by pi0** [comment]
> what files, folders, configs, ... can all be part of a theme? E.g.: can a vitest.config.ts also be specified?

Very good question! vitest.config.ts, etc should be in clonnable theme directory. Nuxt extends has support to extend built-in scanned files (nuxt.config, pages, components, layouts, server, middleware, public, etc). We should document this!

> if a collision happens, what takes precedence? -> you already said user-project here

It depends feature by feature. Something like components, they override. confgs are extended.

**Comment by BracketJohn** [comment]
> configs are extrended

but I guess only certain configs that nuxt knows? E.g., "histoire.config.ts" would be replaced and  ot overwritten?

---

Thanks so far - I think extends/theme will likely be the bext step of sidebase, just for the versioning alone (if it's limitations work out for the template use case, which I guess they do)

For now, I've changed the filename to be community/sidebase.ts above!

**Comment by pi0** [comment]
> but I guess only certain configs that nuxt knows? E.g., "histoire.config.ts" would be replaced and ot overwritten?

Right. Nuxt modules should manually handle custom configs. If not supported, you can keep it in user clonable template until supported.

**Comment by BracketJohn** [comment]
Got it. 

Can we move ahead with merging this PR or is anything blocking this? (:

**Comment by BracketJohn** [comment]
Heyo @pi0 / @Atinux - any indication of when you will have time for a further iteration here?

I don't want to be pushy, and don't expect a certain result, just for my own planning it'd be interesting to get a time range until next iteration happens here.

Thanks for the fruitful discussions so far and enjoy your weekends 😊

**Review by atinux — APPROVED** [review]

**Pull request merged**
